/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package cadastropessoa;

import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Professor
 */
public class TelaCadPessoa extends javax.swing.JInternalFrame {

    private final TelaPrincipal telaPrincipal;
    private int posicao = -1;

    /**
     * Creates new form TelaCadPessoa
     */
    public TelaCadPessoa(TelaPrincipal telaPrincipal) {
        initComponents();
        this.telaPrincipal = telaPrincipal;
        this.posicao = -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Pessoas");
        setVisible(true);

        jLabel1.setText("Nome:");

        jLabel2.setText("Endereço:");
        jLabel2.setToolTipText("");

        jLabel3.setText("E-mail:");

        jButton1.setText("Gravar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Listar Pessoas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("◀");
        jButton3.setToolTipText("Navegar para a pessoa a esquerda");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("▶");
        jButton4.setToolTipText("Navegar para a pessoa a direita");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Excluir Pessoa");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                                .addComponent(txtNome)
                                .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(2, 2, 2)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Gravar
        if(camposPreenchidos()){
            Pessoa pessoa = new Pessoa();
            pessoa.setNome(txtNome.getText());
            pessoa.setEndereco(txtEndereco.getText());
            pessoa.setEmail(txtEmail.getText());
            String mensagem = "";
            //se a variavel posicao == -1 gravar novo registro
            //senão != atualizar registro
            if(posicao == -1){
                //adicionar esta pessoa no array listaPessoas na tela principal;
                telaPrincipal.adicionarPessoaLista(pessoa);
                mensagem = "Pessoa cadastrada com sucesso!";
            }else{
                telaPrincipal.atualizarPessoaLista(pessoa, posicao);
                mensagem = "Pessoa atualizada com sucesso!";
            }
        
            //adicionar esta pessoa no array listaPessoas na tela principal
            limparTela();
            posicao = -1;
            JOptionPane.showMessageDialog(null,
                mensagem);
        }else{
            JOptionPane.showMessageDialog(null,
                    "Preencha todos os campos!");
            posicao = -1;
            limparTela();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Listar pessoas
        listarPessoas();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Navegar para a esquerda
        List<Pessoa> lstPessoa = telaPrincipal.getListaPessoa();
        posicao--; //posicao = posicao -1;
        if(posicao > -1 ){
            Pessoa pessoa = lstPessoa.get(posicao);
            txtNome.setText(pessoa.getNome());
            txtEndereco.setText(pessoa.getEndereco());
            txtEmail.setText(pessoa.getEmail());
        }else{
            JOptionPane.showMessageDialog(null,
                    "Não existem mais pessoas no cadastro");
            posicao = -1;
            limparTela();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Navegar para a direita;
        List<Pessoa> lstPessoa = telaPrincipal.getListaPessoa();
        posicao++; //posicao = posicao +1;
        if(posicao < lstPessoa.size()){
            Pessoa pessoa = lstPessoa.get(posicao);
            txtNome.setText(pessoa.getNome());
            txtEndereco.setText(pessoa.getEndereco());
            txtEmail.setText(pessoa.getEmail());
        }else{
            JOptionPane.showMessageDialog(null,
                    "Não existem mais pessoas no cadastro");
            posicao = -1;
            limparTela();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       //Botao de excluir pessoa
    }//GEN-LAST:event_jButton5ActionPerformed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
    
    //método para limpar os campos da tela
    private void limparTela() {
        txtNome.setText("");
        txtEndereco.setText("");
        txtEmail.setText("");
        txtNome.requestFocusInWindow();
    }
    
    //metodo para exibir todas as pessoas da lista;
    private void listarPessoas(){
        List<Pessoa> lstPessoa = telaPrincipal.getListaPessoa();
        String texto = "";
        for(Pessoa p : lstPessoa){
            //+= ==> texto = texto + concatenar
            texto += p.toString() + "\n -------- \n";
        }
        JOptionPane.showMessageDialog(null,texto);
    }

    private boolean camposPreenchidos() {
        boolean resposta = true;
        //vamos validar os campos.
        if(txtNome.getText().length() == 0){
            resposta = false;
        }
        if(txtEndereco.getText().length() == 0 && resposta){
            resposta = false;
        }
        if(txtEmail.getText().length() == 0 && resposta){
            resposta = false;
        }
        return resposta;
    }
}

